// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkqnoazbjnqstbmdzzpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rcW5vYXpiam5xc3RibWR6enBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjI3MDgsImV4cCI6MjA3MjM5ODcwOH0.8KpAjj00HaN71LkTF537A048YG-SVzJu1IPKv1E7n9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});